<?php
require_once('./template/src/name-entry-section.html');
require_once('./template/src/playing-card-game-section.html');
require_once('./template/src/opening-message-label.html');
require_once('./template/src/playing-card-game-section__card.html');
require_once('./template/src/truth-or-callenge.html');
require_once('./template/src/choice-truth-or-callenge.html');
require_once('./template/src/order-truth-content.html');
require_once('./template/src/order-challenge-content.html');
